apiVersion: v1
description: DevOps all-in-one bundle
name: devops
version: 0.1.0
tillerVersion: ">=2.5.0"
keywords:
- git
- ci
- cd
- deploy
- issue tracker
- code review
- wiki
home: https://about.gitlab.com
sources:
- http://docs.gitlab.com/ce/install/kubernetes/
- https://gitlab.com/charts/charts.gitlab.io
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
maintainers:
- name: Niklaus Hirt
  email: nikh@ch.ibm.com
