apiVersion: v1
entries:
  gitlab-ce:
  - appVersion: 9.3.8-ce.0
    created: 2018-07-16T11:04:45.000604+02:00
    description: GitLab CE release
    digest: 1de7d928b96b986ba0cfe41829797e73cfffb8a6e5c2bc2931ba12a4d33f1033
    home: http://gitlab.com
    icon: https://docs.gitlab.com/assets/images/gitlab-logo.svg
    keywords:
    - git
    - gitlab
    maintainers:
    - email: zhiweik@gmail.com
      name: Zhiwei
    name: gitlab-ce
    sources:
    - https://hub.docker.com/r/gitlab/gitlab-ce
    urls:
    - https://raw.githubusercontent.com/niklaushirt/devopshelm/master/charts/repo/stable/gitlab-ce-0.9.1.tgz
    version: 0.9.1
  jenkins:
  - appVersion: "2.73"
    created: 2018-07-16T11:04:45.001455+02:00
    description: Open source continuous integration server. It supports multiple SCM
      tools including CVS, Subversion and Git. It can execute Apache Ant and Apache
      Maven-based projects as well as arbitrary scripts.
    digest: c79073ff7921a250328253fca0fa6943795451caa25dddcb4c59556c7345513c
    home: https://jenkins.io/
    icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
    maintainers:
    - email: lachlan.evenson@microsoft.com
      name: lachie83
    - email: viglesias@google.com
      name: viglesiasce
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-jnlp-slave
    urls:
    - https://raw.githubusercontent.com/niklaushirt/devopshelm/master/charts/repo/stable/jenkins-0.9.1.tgz
    version: 0.9.1
  urbancode:
  - apiVersion: v1
    created: 2018-07-16T11:04:45.001754+02:00
    description: A Helm chart for IBM UrbanCode Deploy
    digest: 88db88516050c395ee0e9244a82c1bd98b50f97578f1192c6f9f3c522733ff65
    icon: https://github.com/niklaushirt/chartslocal/raw/master/icons/urbancodedeployicon.png
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: urbancode
    sources:
    - https://github.com/niklaushirt/chartslocal
    urls:
    - https://raw.githubusercontent.com/niklaushirt/devopshelm/master/charts/repo/stable/urbancode-6.2.7.tgz
    version: 6.2.7
generated: 2018-07-16T11:04:44.998382+02:00
